---
# Source: go-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hello-string
data:
  hellostr: aGVsbG8=
---
# Source: go-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-chart
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: go-app-chart
  template:
    metadata: 
      labels: 
        app: go-app-chart
    spec:
      containers: 
        - name: go-application
          image: :1.0.0
          env:
          - name: SCR_STR
            valueFrom:
              secretKeyRef:
                name: hello_string
                key: hello
          ports:
            - containerPort: 8080 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
